In [35]:
import torch
import numpy as np
import torch.nn as  nn

In [38]:
input=torch.randn([2,6,640, 480])
input

tensor([[[[-7.2344e-01, -1.6059e+00,  9.6213e-01,  ..., -1.2264e+00,
            9.4439e-01,  6.7397e-01],
          [ 2.3704e-03, -1.3406e+00, -4.3259e-01,  ...,  1.5292e-01,
            3.6566e-01,  8.8932e-01],
          [-9.7524e-01, -6.2530e-01, -5.4170e-01,  ...,  8.9109e-01,
           -7.1782e-01,  5.7678e-01],
          ...,
          [ 1.6370e+00, -2.6376e-01,  6.5157e-01,  ...,  7.0555e-01,
           -9.9904e-01,  1.7348e+00],
          [-9.6965e-01,  7.8059e-01,  1.5657e-01,  ...,  1.5795e+00,
            7.0036e-01,  7.6377e-01],
          [-5.1017e-01,  5.2880e-01,  5.6992e-01,  ...,  3.2024e-01,
            8.9672e-01, -3.0862e-01]],

         [[-9.2276e-01,  2.1332e-01,  6.3675e-01,  ..., -1.0459e+00,
            4.3554e-01,  5.2962e-01],
          [ 1.5285e-01,  7.9987e-02, -1.5124e+00,  ..., -1.2390e-01,
            2.0168e+00, -8.7726e-01],
          [ 4.5355e-01,  4.7231e-01, -2.9361e+00,  ...,  9.9294e-01,
            2.3369e-01, -6.5109e-01],
          ...,
     

In [71]:
output=torch.randn([32, 14, 640, 480])
output

tensor([[[[ 1.5297e+00,  1.1411e+00, -2.8044e-01,  ..., -9.0622e-01,
            1.1560e+00,  2.0729e-01],
          [-2.4645e-01,  1.9345e-01, -1.6018e+00,  ..., -1.5280e+00,
            6.7644e-01, -7.3313e-01],
          [-3.3228e-01,  6.3099e-01, -2.0187e+00,  ..., -3.5831e-01,
           -8.7799e-01, -5.7478e-01],
          ...,
          [-4.2656e-01, -8.6146e-02,  9.1801e-02,  ..., -8.8697e-01,
            7.6895e-01, -1.3824e+00],
          [-1.4642e+00, -1.1018e+00, -1.0548e+00,  ..., -1.4774e+00,
            7.1320e-01, -5.6140e-02],
          [ 1.8057e+00,  1.2634e+00,  1.8325e-01,  ...,  2.2979e-01,
            4.0520e-01, -1.4444e-01]],

         [[ 1.3470e+00,  9.8236e-01, -1.1471e-01,  ..., -5.8227e-01,
            5.9964e-02,  3.2671e-01],
          [-8.9087e-01,  5.4468e-01,  3.9150e-01,  ...,  2.8640e-02,
           -1.3687e+00,  1.0253e+00],
          [ 1.8386e+00,  1.1174e+00,  1.2990e+00,  ..., -7.2235e-01,
            3.4388e-01,  1.6366e-01],
          ...,
     

In [72]:
pred = output.permute(0, 2, 3, 1).contiguous()
print(pred.shape)
print("len(pred)",len(pred))
pred = pred.view(-1, 14)
pred

torch.Size([32, 640, 480, 14])
len(pred) 32


tensor([[ 1.5297,  1.3470, -0.8684,  ..., -1.1779, -0.4560,  0.7336],
        [ 1.1411,  0.9824, -0.2269,  ...,  1.3082,  0.2811,  1.3248],
        [-0.2804, -0.1147,  0.4400,  ...,  0.0451,  0.0238, -1.0239],
        ...,
        [-0.1166,  0.0451,  0.1107,  ..., -0.7856,  0.9585,  1.5933],
        [-0.0368, -0.2754,  1.4233,  ...,  0.6760, -2.5110, -0.2415],
        [-0.1936,  0.3456,  0.9374,  ...,  3.4837,  0.8166, -0.4705]])

In [45]:
pred_max_val, pred_arg_max = pred.max(1)



In [46]:
pred_max_val



tensor([1.5336, 2.0858, 1.9527,  ..., 2.2415, 2.1225, 2.0333])

In [47]:
pred_arg_max



tensor([ 5, 12,  0,  ...,  4, 13,  3])

In [52]:
target=torch.randn([2,640,480])
target

tensor([[[ 0.6213, -0.4556,  0.3886,  ...,  0.8470,  0.8646,  0.4432],
         [-0.1974, -0.1535,  0.8211,  ...,  0.5790,  0.7154,  2.5979],
         [ 1.1218,  0.3137,  1.9347,  ..., -1.6147,  2.0410,  1.7187],
         ...,
         [ 1.0417, -0.3780,  0.9827,  ...,  0.5060, -0.1184,  0.5692],
         [ 1.8262,  2.1548, -0.0969,  ..., -0.3734, -0.8837,  2.7942],
         [ 2.4953,  1.2769, -0.4821,  ..., -0.1990, -0.7380, -0.4479]],

        [[-0.2704,  0.0369, -0.8694,  ...,  0.5239,  0.4036, -0.9856],
         [ 0.0703, -0.6991,  0.9012,  ..., -0.9362, -0.2451, -0.2785],
         [-0.4798,  0.3369,  0.9569,  ...,  0.7755,  0.9652,  0.3686],
         ...,
         [-0.8303,  0.0530,  0.5009,  ..., -1.3917, -0.2493,  0.5911],
         [-0.8329,  0.0860, -0.0921,  ..., -0.2334,  1.7164,  0.3998],
         [-0.2792,  0.8924, -1.0779,  ...,  1.1013, -0.5248,  0.2874]]])

In [51]:
pairs = target.view(-1) * 14 + pred_arg_max.view(-1)  #[ 0]
pairs

tensor([-3.7942, 22.0301,  1.8136,  ..., 11.2717, 21.6117, -9.1456])

In [61]:
confusion_matrix = torch.cuda.FloatTensor(np.zeros(14 ** 2))
# 计算混淆矩阵
for i in range(14 ** 2):
    cumu = pairs.eq(i).float().sum()
    confusion_matrix[i] += cumu.item()


In [58]:
confusion_matrix

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       device='cuda:0')

In [66]:
confusion_matrix = confusion_matrix.reshape((14, 14))
class_iou = np.zeros(14)
confusion_matrix[0, :] = np.zeros(14)
confusion_matrix[:, 0] = np.zeros(14)

# 计算交并比
for i in range(1, 14):
    class_iou[i] = confusion_matrix[i, i] / (np.sum(confusion_matrix[i, :]) + np.sum(confusion_matrix[:, i]) - confusion_matrix[i, i])


C:\Users\32243\AppData\Local\Temp\ipykernel_13756\3578671759.py:8: RuntimeWarning: invalid value encountered in float_scalars
  class_iou[i] = confusion_matrix[i, i] / (np.sum(confusion_matrix[i, :]) + np.sum(confusion_matrix[:, i]) - confusion_matrix[i, i])


In [67]:
class_iou

array([ 0., nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan])